module.exports = {
	PORT: process.env.PORT || 5000,
	MONGO_URL: process.env.MONGO_URL || "mongodb://127.0.0.1:27017/default",
	FRONTEND_URL: process.env.FRONTEND_URL || "https://0.0.0.0:3000",

	ACCESS_SECRET: process.env.ACCESS_SECRET || "secretAccessWord",
	REFRESH_SECRET: process.env.REFRESH_SECRET || "secretRefreshWord",

	NO_REPLAY_EMAIL: process.env.NO_REPLAY_EMAIL,
	NO_REPLAY_EMAIL_PASSWORD: process.env.NO_REPLAY_EMAIL_PASSWORD,

	CONFIRM_ACCOUNT_ACTION_TOKEN_SECRET: process.env.CONFIRM_ACCOUNT_ACTION_TOKEN_SECRET || "CONFIRM_ACCOUNT_ACTION_TOKEN_SECRET",
	FORGOT_PASSWORD_ACTION_TOKEN_SECRET: process.env.FORGOT_PASSWORD_ACTION_TOKEN_SECRET || "FORGOT_PASSWORD_ACTION_TOKEN_SECRET"
};